import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import BottomNav from "../components/BottomNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${geistSans.variable} ${geistMono.variable}`} style={{
        color: 'rgb(var(--foreground-rgb))',
        backgroundColor: '#1a1a2e'
      }}>
        <main style={{ paddingBottom: '80px' }}>{children}</main>
        <BottomNav />
      </body>
    </html>
  );
}
